In [1]:
import numpy as np
a=np.array([10,20,30,12,16,2,100])
a

array([ 10,  20,  30,  12,  16,   2, 100])

In [1]:
# statistics
# mean(),median(),std(),var()
#aggregate
#min(),max()

In [5]:
import numpy as np
a1=np.array([10,20,30],[5,25,32],[100,20,24])
a1

ValueError: only 2 non-keyword arguments accepted

In [ ]:
# all and any
print("return the true when all ")

In [10]:
a=np.zeros([5,5])
print(a)
print(np.any(a==0))
print(np.any(a!=0))
print(np.all(a==0))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True
False
True


In [12]:
a=np.array([10e3]) # 10*10**3
a

a=np.array([1e3,2e3,5e3])
a

array([1000., 2000., 5000.])

In [22]:
a=np.array([10,20,30,40])
np.savetxt("save.txt",a)

In [23]:
s=np.loadtxt('save.txt')
s

array([10., 20., 30., 40.])

In [26]:
# ravel()
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("data type:",a.dtype)
print("data dimention:",a.ndim)

print("convert 2d to 1d:",a)

[[1 2 3]
 [4 5 6]]
data type: int32
data dimention: 2
convert 2d to 1d: [[1 2 3]
 [4 5 6]]


In [29]:
a.T   # convert rows as colums

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
l1=[1,2,3]
l2=[20,30,40]
#l1+l2
a1=np.array(l1)
a2=np.array(l2)

a1+a2
a1*a2
a1-a2

array([-19, -28, -37])

In [38]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(a1)
print(a2)
a1+a2


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

### numpy topics coverd:

* what is data types of data represnt of data
* how to create numpy array as 1d,2d,3d.....ndimensional
* data types
* type conversion
* arrabge,linspace,eye,diag
* how toacces dataa using indexing
* statatics and aggregations
* save and load
* ravel,transpose
* mathematics

###  Pandas:

* pandas is python libray for creating datasets(table)
* pandas library is more efficience and effective in data science
* Pandas provide EDA(Exploratory Data Analysis)
* How to use pandas 
          * library(pip install pandas)


### Types:

* pandas is type
    * series : is nothing but 1d array
    * data frame: it is nothing but d array
    
### what is  Data-set:
* data 

In [40]:
import numpy as np
import pandas as pd
pd.__version__

'1.0.1'

In [42]:
# List
l=[10,20,30,40,50,60,70,80]
s=pd.Series(l)
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [47]:
# numpy
a=np.array([100,200,300,400,500.50])
s=pd.Series(a)
s

a=np.array([100,200,300,400,500.90])
s=pd.Series(a)
s

a=np.array([100,200,300,400,500.50,"hai"])
s=pd.Series(a)
s

a=np.array([100,200,300,400,500.50,True])
s=pd.Series(a)
s

a=np.array(['100',200,300,400,500.50])
s=pd.Series(a)
s

0      100
1      200
2      300
3      400
4    500.5
dtype: object

In [48]:
type(s)

pandas.core.series.Series

In [49]:
s.dtype

dtype('O')

In [50]:
s.shape

(5,)

In [51]:
len(s)

5

In [52]:
min(s)

'100'

In [53]:
max(s)

'500.5'

In [56]:
# how to access the data from the series
a=np.array([100,200,300,400,500.50])
s=pd.Series(a)
s[0]
s[1:]

1    200.0
2    300.0
3    400.0
4    500.5
dtype: float64